var countries = {

"ADL":"Adelaide - ADL",
"ASP":"Alice Springs - ASP",
"BNK":"Ballina/Byron Bay - BNK",
"BNE":"Brisbane - BNE",
"BME":"Broome - BME",
"BDB":"Bundaberg - BDB",
"CNS":"Cairns - CNS",
"CBR":"Canberra - CBR",
"XCH":"Christmas Island - XCH",
"CCK":"Cocos Island - CCK",
"CFS":"Coffs Harbour - CFS",
"DRW":"Darwin - DRW",
"EMD":"Emerald - EMD",
"GLT":"Gladstone - GLT",
"OOL":"Gold Coast - OOL",
"HTI":"Hamilton Island - HTI",
"HBA":"Hobart - HBA",
"KGI":"Kalgoorlie - KGI",
"KTA":"Karratha - KTA",
"KNX":"Kanunurra - KNX",
"LST":"Launceston - LST",
"MKY":"Mackay - MKY",
"MEL":"Melbourne - MEL",
"ISA":"Mount Isa - ISA",
"NTL":"Newcastle/Port Stephens - NTL",
"ZNE":"Newman - ZNE",
"ONS":"Onslow - ONS",
"PER":"Perth - PER",
"PHE":"Port Hedland - PHE",
"PPP":"Proserpine (Whitsunday Coast) - PPP",
"ROK":"Rockhampton - ROK",
"CUD":"Sunshine Coast - CUD",
"SYD":"Sydney - SYD",
"TSV":"Townsville - TSV",  
}
